# Generated by Django 5.1.6 on 2025-02-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='activation_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='activation code'),
        ),
    ]
