# Generated by Django 4.2 on 2025-02-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='main description of this task')),
                ('title', models.CharField(max_length=200, verbose_name='title of this task')),
                ('deadline', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False, verbose_name='is this subtask complete')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='main description of this task')),
                ('title', models.CharField(max_length=200, verbose_name='title of this task')),
                ('deadline', models.DateTimeField()),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
