# Generated by Django 4.2 on 2025-02-14 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_module', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_task',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='task_module.task'),
        ),
    ]
