# Generated by Django 4.2 on 2025-02-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_module', '0003_alter_sub_task_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_modification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='when was the last time this task got modified'),
        ),
    ]
